update
takahiroanno2024/tokyoai-analysis pull request #2
Opened 2024-06-25 08:05 UTC by nishio

2024-06-25 16:54 UTC, nanocloudx requested changes
index.html については、ファイルサイズは肥大化してしまいますが、整形したものをコミットいただけると助かります！
（レビューのしやすさと、後々発生しうる微修正時の diff を確認しやすくする意図）

2024-06-25 16:54 UTC, nanocloudx commented on 20240625-qt-to-manifesto/index.html
> +<!DOCTYPE html><html><head><meta charSet="utf-8"/><meta name="viewport" content="width=device-width"/><meta name="next-head-count" content="2"/><link rel="preload" href="./_next/static/css/1872bb4c65
OGP 対応のため `<head>` タグは `<head prefix="og: https://ogp.me/ns#">` とする必要があります

2024-06-25 16:54 UTC, nanocloudx commented on 20240625-qt-to-manifesto/ogp.png
問題ないです！
が、他とのトンマナを揃える観点も多少なり必要と考えていますので、デザイナーへの依頼も検討したいですね

2024-06-25 23:52 UTC, nishio commented on 20240625-qt-to-manifesto/ogp.png
素材の背景画像を共有してください。それがないのでやりようがなくて困っています。

2024-06-25 23:55 UTC, nishio commented on 20240625-qt-to-manifesto/index.html
> +<!DOCTYPE html><html><head><meta charSet="utf-8"/><meta name="viewport" content="width=device-width"/><meta name="next-head-count" content="2"/><link rel="preload" href="./_next/static/css/1872bb4c65
✅

2024-06-26 02:36 UTC, nanocloudx approved these changes
LGTM！

2024-06-26 02:36 UTC, merged